# Generated by Django 3.2.9 on 2021-11-27 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('store_name', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='store_book/')),
                ('fav', models.BooleanField()),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
