# Generated by Django 3.2.9 on 2021-11-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='author',
        ),
    ]
