# Generated by Django 3.2.9 on 2021-11-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_name_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='name',
        ),
    ]
